[package]
name = "smolbigint"
version = "0.1.0"
edition = "2024"

[dependencies]
num-traits = { version = "0.2.19", optional = true, default-features = false }

[features]
default = ["num-traits"]
num-traits = ["dep:num-traits"]
